### ISSUE TITLE
NPE in Goland beta

### ISSUE THREAD

**Issue by stokito** [SJrX/systemdUnitFilePlugin#114]
I using EAP version of Goland and got an NPE after start.
GoLand 2021.2.2
Build #GO-212.5080.74, built on August 31, 2021
Runtime version: 11.0.11+9-b1504.16 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

```
update failed for AnAction(com.intellij.ide.actions.ExternalJavaDocAction, id=ExternalJavaDoc) with text=External Documentation

java.lang.NullPointerException
at net.sjrx.intellij.plugins.systemdunitfiles.documentation.UnitFileDocumentationProvider.getUrlFor(UnitFileDocumentationProvider.java:76)
at com.intellij.lang.documentation.CompositeDocumentationProvider.getUrlFor(CompositeDocumentationProvider.java:127)
at com.intellij.lang.documentation.CompositeDocumentationProvider.hasUrlsFor(CompositeDocumentationProvider.java:277)
at com.intellij.ide.actions.ExternalJavaDocAction.update(ExternalJavaDocAction.java:153)
at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performDumbAwareUpdate$0(ActionUtil.java:130)
at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:144)
at com.intellij.openapi.actionSystem.impl.ActionUpdater.doUpdate(ActionUpdater.java:584)
at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$updateActionReal$7(ActionUpdater.java:132)
at com.intellij.openapi.actionSystem.impl.ActionUpdater.callAction(ActionUpdater.java:176)
at com.intellij.openapi.actionSystem.impl.ActionUpdater.updateActionReal(ActionUpdater.java:133)
at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$new$0(ActionUpdater.java:113)
at com.intellij.openapi.actionSystem.impl.ActionUpdater.update(ActionUpdater.java:570)
```

If this is related to the service file that I have I can provide it. But it's very basic and simple

**Comment by SJrX** [comment]
Hi there,

If you could provide the service file I'd appreciate it as well a screenshot of where your cursor is when you get this error and the action you take. If not that's fine there is probably a less than 20% chance I can't figure it out from the stack trace. 

Thanks for the report.

**Comment by stokito** [comment]
I can't reproduce it so let's just forget it. If anyone got the same issue let's just reopen

**Comment by SJrX** [comment]
I'll still take a look at it.

**Comment by SJrX** [comment]
Welp, I couldn't reproduce it directly, and I didn't want to dig into finding some way the PsiElement.getNode() could be null in this specific case, but it is 100% allowed by the interface, and so I just patched out the issue directly.

Want to do a bunch of random infrastructure tweaks so not sure when I'll get around to pushing this out

**Comment by stokito** [comment]
Thank you, the issue is not critical and never occurred again so I just want you to keep your time :)
I reported it just to see if anyone else got the same.

**Comment by SJrX** [comment]
Yup I'm happy you reported it :)
