### ISSUE TITLE
Fix build failures

### ISSUE THREAD

**Issue by SJrX** [SJrX/systemdUnitFilePlugin#201]
All builds are failing likely due to an upstream issue.

```
***** (Code but not doc) *****

11:42:52,659 SEVERE                 #TestFramework - test failed: Comparison Failure 
Actual [[Mount.DefaultStartupMemoryLow 
Service.DefaultStartupMemoryLow 
Slice.DefaultStartupMemoryLow 
Socket.DefaultStartupMemoryLow 
Swap.DefaultStartupMemoryLow 
]] 
Expected [[<empty>]] 
 
org.junit.ComparisonFailure: Expected that everything in the code was in the documentation, but we are missing the following: expected:<[<empty>]> but was:<[Mount.DefaultStartupMemoryLow 
Service.DefaultStartupMemoryLow 
Slice.DefaultStartupMemoryLow 
Socket.DefaultStartupMemoryLow 
Swap.DefaultStartupMemoryLow 
]> 
	at org.junit.Assert.assertEquals(Assert.java:117) 
	at com.intellij.testFramework.UsefulTestCase.assertOrderedEquals(UsefulTestCase.java:603) 
	at com.intellij.testFramework.UsefulTestCase.assertOrderedEquals(UsefulTestCase.java:593) 
	at com.intellij.testFramework.UsefulTestCase.assertEmpty(UsefulTestCase.java:853) 
	at net.sjrx.intellij.plugins.systemdunitfiles.semanticdata.SemanticDataDocumentationCompletionTest.testAllOptions(SemanticDataDocumentationCompletionTest.kt:29) 
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) 
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) 
	at junit.framework.TestCase.runTest(TestCase.java:177) 
	at com.intellij.testFramework.UsefulTestCase.lambda$runBare$11(UsefulTestCase.java:484) 
	at com.intellij.testFramework.UsefulTestCase.lambda$wrapTestRunnable$13(UsefulTestCase.java:505) 
	at com.intellij.testFramework.UsefulTestCase.runTestRunnable(UsefulTestCase.java:409) 
	at com.intellij.testFramework.fixtures.BasePlatformTestCase.runTestRunnable(BasePlatformTestCase.java:105) 
	at com.intellij.testFramework.UsefulTestCase.defaultRunBare(UsefulTestCase.java:425) 
	at com.intellij.testFramework.UsefulTestCase.lambda$runBare$12(UsefulTestCase.java:492) 
	at com.intellij.testFramework.EdtTestUtil.lambda$runInEdtAndWait$1(EdtTestUtil.java:40) 
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:308) 
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771) 
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722) 
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716) 
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399) 
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) 
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741) 
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:389) 
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) 
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) 
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) 
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) 
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) 
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90) 
 


Expected that everything in the code was in the documentation, but we are missing the following: expected:<[<empty>]> but was:<[Mount.DefaultStartupMemoryLow
Service.DefaultStartupMemoryLow
Slice.DefaultStartupMemoryLow
Socket.DefaultStartupMemoryLow
Swap.DefaultStartupMemoryLow
]>
<Click to see difference>
```

**Comment by SJrX** [comment]
Upstream bug report filed: https://github.com/systemd/systemd/issues/26493
